### ISSUE TITLE
add problem matcher

### ISSUE THREAD

**Issue by korelstar** [ChristophWurst/xmllint-action#1]
I've created a [problem matcher for `xmllint`](https://github.com/marketplace/actions/xmllint-problem-matcher). This means, that all errors found by `xmllint` will be shown as annotation at the respective file and code line in GitHub Actions.

I think it would be cool if this problem matcher is automatically activated in your action. Here you can see how this works in a workflow: https://github.com/nextcloud/notes/pull/465/commits/911ec037c692ce00b621f79fe8222ab35beab6ca (but I don't know how to do this in a docker action)

**Comment by ChristophWurst** [comment]
Nice! I'm not sure I can use *your* problem matcher here, but it should be possible from Docker as well: https://github.com/actions/toolkit/blob/master/docs/commands.md#problem-matchers.

**Comment by ChristophWurst** [comment]
https://github.com/actions/toolkit/pull/341/files#diff-4d65444af0929ef2149f52c8909c8914R131 might help. I'd have to read up on what the json file does and how we could generate one.

**Comment by korelstar** [comment]
The json file can be this one: https://github.com/korelstar/xmllint-problem-matcher/blob/master/xmllint-matcher.json

**Comment by jonasbn** [comment]
I just tested the [xmllint-problem-matcher](https://github.com/korelstar/xmllint-problem-matcher) on [my own XMLLint action](https://github.com/DK-Hostmaster/epp-xsd-files) and it looks AWESOME! well except for the fact that _my_ XML has issues :-)
