### ISSUE TITLE
possible to add options for relaxng and schematron validation?

### ISSUE THREAD

**Issue by rlskoeser** [ChristophWurst/xmllint-action#5]
`xmllint` supports both of these; it looks like it would be a fairly simple matter of adding and handling the different options. 

Willing to work on a PR if you can advise on how to approach and how to test.

**Comment by ChristophWurst** [comment]
I'm not an expert of xmllint nor Github actions but the Github docs should guide you through the process of adding new, optional arguments: https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action

**Comment by rlskoeser** [comment]
added in PR #6
